shader_type canvas_item;

uniform float radius_scale: hint_range(0.0, 1.0, 0.05) = 0.1;
uniform bool rounded_corner_top_left = true;
uniform bool rounded_corner_top_right = true;
uniform bool rounded_corner_bottom_left = true;
uniform bool rounded_corner_bottom_right = true;
uniform float width = 1.0;
uniform float height = 1.0;

void fragment() {
	vec4 tex_color = texture(TEXTURE, UV);
	vec2 pos = vec2(UV.x * width, UV.y * height);
	float radius = min(width, height) * radius_scale / 2.0;
	float dist;

	// Top left corner
	if (rounded_corner_top_left) {
		dist = length(pos - vec2(radius));
		if (dist > radius && pos.x < radius && pos.y < radius) {
			tex_color.a = 0.0;
		}
	}

	// Top right corner
	if (rounded_corner_top_right) {
		dist = length(pos - vec2(width - radius, radius));
		if (dist > radius && pos.x > width - radius && pos.y < radius) {
			tex_color.a = 0.0;
		}
	}

	// Bottom left corner
	if (rounded_corner_bottom_left) {
		dist = length(pos - vec2(radius, height - radius));
		if (dist > radius && pos.x < radius && pos.y > height - radius) {
			tex_color.a = 0.0;
		}
	}

	// Bottom right corner
	if (rounded_corner_bottom_right) {
		dist = length(pos - vec2(width - radius, height - radius));
		if (dist > radius && pos.x > width - radius && pos.y > height - radius) {
			tex_color.a = 0.0;
		}
	}

	COLOR = tex_color * COLOR; // This makes modulation work
}
